<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "redirects".
 *
 * @property integer $id
 * @property integer $system
 * @property integer $offer_id
 * @property string  $date_redirected
 * @property string  $ip
 * @property string  $user_agent
 */
class Redirects extends ActiveRecord {

	/**
	 * @inheritdoc
	 */
	public static function tableName () {
		return 'redirects';
	}

	/**
	 * @inheritdoc
	 */
	public function rules () {
		return [
			[['system', 'offer_id'], 'required'],
			[['system', 'offer_id'], 'integer'],
			[['date_redirected'], 'safe'],
			[['ip', 'user_agent'], 'string', 'max' => 255]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels () {
		return [
			'id'              => 'ID',
			'system'          => 'System',
			'offer_id'        => 'Offer ID',
			'date_redirected' => 'Date Redirected',
			'ip'              => 'Ip',
			'user_agent'      => 'User Agent',
		];
	}

	public function beforeSave ($insert) {
		if($this->getIsNewRecord()) {
			$this->date_redirected = date('Y-m-d H:i:s');
			$this->ip = \Yii::$app->request->userIP;
			$this->user_agent = \Yii::$app->request->userAgent;
		}
		return parent::beforeSave($insert); // TODO: Change the autogenerated stub
	}
}
